title: Backstreets & Bitumen
author: Damian Johns
email: damian@damo-maker.github.io
description: > # this means to ignore newlines until "baseurl:"
  Melbourne, Australia, a street level view.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
